#!/usr/bin/env node
// Convert the v1 single-KV-blob export into D1 seed SQL (REWRITE_PLAN.md §8).
//
//   npx wrangler kv key get all_app_data --remote --binding MEETING_DB > kv_export.json
//   node scripts/migrate_kv_to_d1.mjs kv_export.json > seed.sql
//   npx wrangler d1 execute meeting_db_dev --local  --file seed.sql   # verify first
//   npx wrangler d1 execute meeting_db_dev --remote --file seed.sql
//
// Password hashes are carried across verbatim. The live data is mostly bare 64-char
// SHA-256, which the verification chain in auth/crypto.ts still accepts and upgrades to
// pbkdf2c on next successful login. Rewriting or dropping them here would lock everyone
// out, since there is no plaintext to re-hash from.

import { readFileSync } from 'node:fs';

const STORAGE_KEYS = {
  users: 'hc_health_users_v5',
  rooms: 'hc_health_rooms_v5',
  depts: 'hc_health_depts_v5',
  reservations: 'hc_health_reservations_v5',
  equip: 'hc_health_equip_v5',
};

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node scripts/migrate_kv_to_d1.mjs <kv_export.json> > seed.sql');
  process.exit(1);
}

const raw = JSON.parse(readFileSync(inputPath, 'utf8'));
// `wrangler kv key get` may emit the value directly or wrapped in {value: "..."}.
const data = typeof raw === 'string' ? JSON.parse(raw) : raw.value ? JSON.parse(raw.value) : raw;

const q = (v) => (v === null || v === undefined || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v, fallback = 0) => {
  const parsed = Number.parseInt(v, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
};

/** "08:30" -> 510. Integers sort and compare correctly; the string form does not. */
function timeToMinutes(value) {
  if (typeof value !== 'string' || !value.includes(':')) return null;
  const [h, m] = value.split(':').map((x) => Number.parseInt(x, 10));
  if (!Number.isFinite(h) || !Number.isFinite(m)) return null;
  return h * 60 + m;
}

/** v1 stored local-time "YYYY-MM-DD HH:mm" (or nothing at all); D1 stores ISO 8601 UTC. */
function toIso(value) {
  if (!value) return new Date().toISOString();
  const parsed = new Date(String(value).replace(' ', 'T'));
  return Number.isNaN(parsed.getTime()) ? new Date().toISOString() : parsed.toISOString();
}

const slug = (prefix, i) => `${prefix}-${i + 1}`;
const out = [];
const warn = (msg) => process.stderr.write(`warning: ${msg}\n`);

out.push('-- Generated by scripts/migrate_kv_to_d1.mjs. Review before applying.');
out.push('PRAGMA foreign_keys = OFF;');
out.push('BEGIN TRANSACTION;');

// ---- departments -----------------------------------------------------------------
// v1 stored a department as a free-text string on each user. D1 needs a real row so
// users can carry a foreign key.
const deptRows = data[STORAGE_KEYS.depts] ?? [];
const deptIdByName = new Map();

deptRows.forEach((d, i) => {
  const name = typeof d === 'string' ? d : d.name;
  if (!name) return;
  const id = (typeof d === 'object' && d.id) || slug('dept', i);
  deptIdByName.set(name, id);
  const phone = typeof d === 'object' ? d.phone ?? d.ext ?? null : null;
  out.push(
    `INSERT OR REPLACE INTO departments (id, name, phone, sort_order) VALUES (${q(id)}, ${q(name)}, ${q(phone)}, ${i + 1});`
  );
});

/** Departments referenced by a user but absent from the department list still need a row. */
function ensureDept(name) {
  if (!name) return null;
  if (deptIdByName.has(name)) return deptIdByName.get(name);
  const id = `dept-auto-${deptIdByName.size + 1}`;
  deptIdByName.set(name, id);
  warn(`department "${name}" was referenced but not listed; created ${id}`);
  out.push(
    `INSERT OR REPLACE INTO departments (id, name, phone, sort_order) VALUES (${q(id)}, ${q(name)}, NULL, 999);`
  );
  return id;
}

// ---- rooms -----------------------------------------------------------------------
// v1 derived a room's colour from a string hash, so two rooms could collide. Assign
// from the fixed cat-1..6 scale instead (§6.3).
const roomRows = data[STORAGE_KEYS.rooms] ?? [];
const roomIdByName = new Map();

roomRows.forEach((r, i) => {
  const name = typeof r === 'string' ? r : r.name;
  if (!name) return;
  const id = (typeof r === 'object' && r.id) || slug('room', i);
  roomIdByName.set(name, id);
  const capacity = typeof r === 'object' ? n(r.capacity, 0) : 0;
  const location = typeof r === 'object' ? r.location ?? null : null;
  out.push(
    `INSERT OR REPLACE INTO rooms (id, name, capacity, location, color_key, is_active) VALUES (${q(id)}, ${q(name)}, ${capacity}, ${q(location)}, ${q(`cat-${(i % 6) + 1}`)}, 1);`
  );
});

// ---- equipment -------------------------------------------------------------------
const equipRows = data[STORAGE_KEYS.equip] ?? [];
const equipIdByName = new Map();

equipRows.forEach((e, i) => {
  const name = typeof e === 'string' ? e : e.name;
  if (!name) return;
  const id = (typeof e === 'object' && e.id) || slug('eq', i);
  equipIdByName.set(name, id);
  out.push(
    `INSERT OR REPLACE INTO equipment (id, name, is_active, sort_order) VALUES (${q(id)}, ${q(name)}, 1, ${i + 1});`
  );
});

function ensureEquipment(name) {
  if (!name) return null;
  if (equipIdByName.has(name)) return equipIdByName.get(name);
  const id = `eq-auto-${equipIdByName.size + 1}`;
  equipIdByName.set(name, id);
  warn(`equipment "${name}" was referenced but not listed; created ${id}`);
  out.push(
    `INSERT OR REPLACE INTO equipment (id, name, is_active, sort_order) VALUES (${q(id)}, ${q(name)}, 1, 999);`
  );
  return id;
}

// ---- users -----------------------------------------------------------------------
const userRows = data[STORAGE_KEYS.users] ?? [];
const knownUserIds = new Set();
let plaintextCount = 0;

userRows.forEach((u) => {
  if (!u?.id) return;
  knownUserIds.add(String(u.id));

  const deptId = ensureDept(u.dept) ?? 'dept-1';
  const role = ['superadmin', 'admin', 'staff'].includes(u.role) ? u.role : 'staff';
  const hash = u.password ?? u.passwordHash ?? '';

  // A stored value that is not one of the recognised hash formats is almost certainly a
  // leftover plaintext password. The v2 verification chain has no plaintext branch, so
  // such an account cannot log in and must be reset by an administrator.
  const looksHashed =
    /^pbkdf2c?\$/.test(hash) || /^v[12]\$/.test(hash) || /^[a-f0-9]{64}$/i.test(hash);
  if (hash && !looksHashed) {
    plaintextCount++;
    warn(`user ${u.id} has an unrecognised password format; they will need a reset`);
  }

  const createdAt = toIso(u.createdAt);
  out.push(
    `INSERT OR REPLACE INTO users (id, name, dept_id, ext, email, role, password_hash, must_change_password, is_active, created_at, updated_at, password_expires_at) VALUES (${q(u.id)}, ${q(u.name ?? u.id)}, ${q(deptId)}, ${q(u.ext)}, ${q(u.email)}, ${q(role)}, ${q(hash)}, ${hash && looksHashed ? 0 : 1}, 1, ${q(createdAt)}, ${q(createdAt)}, NULL);`
  );
});

// ---- reservations ----------------------------------------------------------------
const reservationRows = data[STORAGE_KEYS.reservations] ?? [];
let skipped = 0;

reservationRows.forEach((r, i) => {
  const startMin = timeToMinutes(r.startTime);
  const endMin = timeToMinutes(r.endTime);

  if (startMin === null || endMin === null || endMin <= startMin) {
    warn(`reservation ${r.id ?? i} has an unusable time range (${r.startTime}-${r.endTime}); skipped`);
    skipped++;
    return;
  }

  const roomId = r.roomId ?? roomIdByName.get(r.roomName);
  if (!roomId) {
    warn(`reservation ${r.id ?? i} references unknown room "${r.roomName}"; skipped`);
    skipped++;
    return;
  }

  // Reservations must reference a real user because of the FK on user_id.
  const userId = String(r.userId ?? '');
  if (!knownUserIds.has(userId)) {
    warn(`reservation ${r.id ?? i} references unknown user "${userId}"; skipped`);
    skipped++;
    return;
  }

  const id = r.id ?? `res-migrated-${i + 1}`;
  const createdAt = toIso(r.createdAt);

  out.push(
    `INSERT OR REPLACE INTO reservations (id, room_id, user_id, date, start_min, end_min, reason, meeting_type, headcount, notes, attendees_email, status, created_at, updated_at, cancelled_at, cancelled_by) VALUES (${q(id)}, ${q(roomId)}, ${q(userId)}, ${q(r.date)}, ${startMin}, ${endMin}, ${q(r.reason ?? '（未填寫）')}, ${q(r.meetingType ?? 'internal')}, ${n(r.headcount, 1)}, ${q(r.notes)}, ${q(r.attendeesEmail)}, 'active', ${q(createdAt)}, ${q(createdAt)}, NULL, NULL);`
  );

  // v1 kept equipment as an array of display names on the reservation itself.
  for (const eqName of r.equipment ?? []) {
    const eqId = ensureEquipment(eqName);
    if (eqId) {
      out.push(
        `INSERT OR IGNORE INTO reservation_equipment (reservation_id, equipment_id) VALUES (${q(id)}, ${q(eqId)});`
      );
    }
  }
});

out.push('COMMIT;');
out.push('PRAGMA foreign_keys = ON;');

process.stdout.write(out.join('\n') + '\n');

process.stderr.write(
  `\nMigration summary:\n` +
    `  departments  ${deptIdByName.size}\n` +
    `  rooms        ${roomIdByName.size}\n` +
    `  equipment    ${equipIdByName.size}\n` +
    `  users        ${knownUserIds.size}` +
    (plaintextCount ? ` (${plaintextCount} need a password reset)` : '') +
    `\n` +
    `  reservations ${reservationRows.length - skipped}` +
    (skipped ? ` (${skipped} skipped — see warnings above)` : '') +
    `\n`
);
